### ISSUE TITLE
self.fully_qualified_url() on Slugged model is busted

### ISSUE THREAD

**Issue by palewire** [newsapps/django-boundaryservice#37]
[Here](https://github.com/datadesk/django-boundaryservice/blob/master/boundaryservice/models.py#L54). Because there is no `get_absolute_url` on the default models.

``` python
>>> Boundary.objects.all()[0].fully_qualified_url()                                                                                                                 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ben/Code/foo/src/django-boundaryservice/boundaryservice/models.py", line 55, in fully_qualified_url
    return get_site_url_root() + self.get_absolute_url()
AttributeError: 'Boundary' object has no attribute 'get_absolute_url'
```

**Comment by palewire** [comment]
Closing as stale.
